service: bidit-queue-handler

plugins:
  - serverless-appsync-plugin

provider:
  name: aws
  region: ap-northeast-2
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  stage: prod
  profile: ${self:custom.profiles.${sls:stage}}
  memorySize: 1536
  timeout: 75
  logRetentionInDays: 60
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - lambda:*
        - s3:*
      Resource:
        - arn:aws:lambda:${self:provider.region}:*:*
    - Effect: Allow
      Action: secretsmanager:GetSecretValue
      Resource:
        - arn:aws:secretsmanager:*:*
    - Effect: Allow
      Action:
        - SQS:*
      Resource:
        - arn:aws:sqs:${self:provider.region}:*:*

  environment:
    REGION: "${self:provider.region}"
    STAGE: "${self:provider.stage}"
    APPSYNC_NAME: "${self:service}-appsync"


custom:
  nodeOption: "--report-uncaught-exception --report-on-fatalerror --report-on-signal"
  profiles:
    dev: biditDev
    prod: bidit


package:
  individually: true
  exclude:
    - ./**

functions:
  bidHandler:
    handler: bundle/bidHandler.bidHandler
    name: bidit-bidHandler
    maximumRetryAttempts: 0
    timeout: 30
    package:
      include:
        - ./bundle/bidHandler.js
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - biditBidQueue
              - Arn
    environment:
      NODE_OPTIONS: ${self:custom.nodeOption}
      BIDIT_SECRET_MANAGER_RDS: ${env:BIDIT_SECRET_MANAGER_RDS}
      BIDIT_RDS_MAIN_HOST: ${env:BIDIT_RDS_MAIN_HOST}
      BIDIT_RDS_MAIN_PORT: ${env:BIDIT_RDS_MAIN_PORT}
      BIDIT_RDS_MAIN_USER: ${env:BIDIT_RDS_MAIN_USER}
      BIDIT_RDS_MAIN_PASS: ${env:BIDIT_RDS_MAIN_PASS}
      BIDIT_RDS_MAIN_DATABASE: ${env:BIDIT_RDS_MAIN_DATABASE}
      BIDIT_SQS_BID_QUEUE: https://sqs.ap-northeast-2.amazonaws.com/164739657386/biditBidQueue

resources:
  Resources:
    biditBidQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        VisibilityTimeout: 35
        QueueName: "biditBidQueue"